# Indexação de DataFrames

Como vimos, tanto Séries como DataFrames podem ter índices aplicados. O índice é basicamente um rótulo de cada linha, e sabemos que linhas correspodem ao eixo (axis) zero. <br>
Os índices podem ser gerados automaticamente quando criamos uma nova série sem um índice e, nesse caso, obtemos um valor numérico, ou eles podem ser definitos explicitamente quando usamos o objeto dicionário e criamos uma nova Série ou quando carregamos arquivo CSV e definimos os parâmetros apropriados. <br>
Outra opção para configuração de um índice é usar a função set_index(). Essa função usa uma lista de colunas como parâmetro e promove tais colunas como índice.

In [32]:
# Importanto a biblioteca
import pandas as pd

In [33]:
# A função set_index() é um processo destrutivo, e não mantém o índice atual. Se você quiser manter o índice atual, precisa criar manualmente uma nova coluna e copiar nela os valores do atributo índice.

df = pd.read_csv('datasets/Admission_Predict.csv', index_col = 0)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [34]:
# Vamos supor que não queremos mais como índice do DataFrame o número de serial, mas, em vez disso, a coluna "Chance of Admit", porém vamos manter a coluna "Serial No." para usar depois. Logo, iremos preservar a coluna "Serial No." em uma nova coluna.
# Podemos fazer isso usando o operador de indexação com a str que é o nome da coluna. Usaremos a função set_index para atribuir como índice a coluna "Chance of Admit"

# Copiando os dados da coluna índice para a nova coluna
df['Numero de Série'] = df.index

# Agora podemos definir como o índice uma outra coluna, sem que perdessemos o índice inicial
df.set_index('Chance of Admit ', inplace = True)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Numero de Série
Chance of Admit,,,,,,,,
0.92,337,118,4,4.5,4.5,9.65,1,1
0.76,324,107,4,4.0,4.5,8.87,1,2
0.72,316,104,3,3.0,3.5,8.00,1,3
0.80,322,110,3,3.5,2.5,8.67,1,4
0.65,314,103,2,2.0,3.0,8.21,0,5

Lembrando que o inplace é para a mudança ocorrer no DataFrame original, uma vez que a função set_index retorna uma cópia, sem alteração do original.

Vemos que criamos um novo índice de uma coluna existente, e o índice tem o mesmo nome da coluna.

In [35]:
# Podemos resetar o índice usando a função reset_index(). Ela promove o índice, tornando-o uma coluna e cria uma coluna índice padrão numerada.
df.reset_index(inplace = True)
df.head()

,Chance of Admit,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Numero de Série
0,0.92,337,118,4,4.5,4.5,9.65,1,1
1,0.76,324,107,4,4.0,4.5,8.87,1,2
2,0.72,316,104,3,3.0,3.5,8.00,1,3
3,0.80,322,110,3,3.5,2.5,8.67,1,4
4,0.65,314,103,2,2.0,3.0,8.21,0,5

Perceba que "Chance of Admit" é promovida de volta como uma coluna e temos um índice numérico

In [36]:
# Um bom recurso do Pandas é a indexação em multi-nível. Isso é semelhante ao uso de chaves compostas em sistemas de bancos de dados relacionais. 
# Para cria um índice multi-nível nós usamos set_index() e informamos a lista de colunas que estamos interessados

df = pd.read_csv('datasets/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [37]:
# Por exemplo, nesse conjunto de dados, há dois níveis de sumarização, um que contém dados sumarizados (informações brutas condensadas) de todo o país, e outro que contém dados sumarizados de cada estado.
# Queremos ver a lista de todos os valores únicos em uma determinada coluna. 
# Nesse DataFrame, vemos que os possíveis valores para a coluna "SUMLEV" usando a função unique()

df["SUMLEV"].unique()

array([40, 50])

Perceba que o resultado nos mostra dois valores apenas, ou seja, a coluna "SUMLEV" só tem dois valores possíveis, ou 40 (Estado) ou 50 (Condado).

In [38]:
# Vamos excluir todas as linhas que são resumos no nível estadual e mantenhamos dados de condados. 
df = df[df['SUMLEV'] == 50]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [39]:
# Além disso, enquanto esse conjunto de dados for interessante por um número de diferentes razões, vamos reduzir nosso conjunto de dados para ver apenas o total de estimativas populacionais e o número total de nascimentos.

# Podíamos excluir todas as colunas que não queremos, porém, neste caso, como existem muitas, é mais fácil escrever as que queremos manter.
# Podemos começar criando uma lista de nomes das colunas que queremos manter
colunas_matidas = ['STNAME','CTYNAME','BIRTHS2010','BIRTHS2011','BIRTHS2012','BIRTHS2013',
                   'BIRTHS2014','BIRTHS2015','POPESTIMATE2010','POPESTIMATE2011',
                   'POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']

df = df[colunas_matidas]
df.head()

,STNAME,CTYNAME,BIRTHS2010,BIRTHS2011,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Alabama,Autauga County,151,636,615,574,623,600,54660,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,517,2187,2092,2160,2186,2240,183193,186659,190396,195126,199713,203709
3,Alabama,Barbour County,70,335,300,283,260,269,27341,27226,27159,26973,26815,26489
4,Alabama,Bibb County,44,266,245,259,247,253,22861,22733,22642,22512,22549,22583
5,Alabama,Blount County,183,744,710,646,618,603,57373,57711,57776,57734,57658,57673

In [40]:
# Os dados do Censo dos EUA possibilitam separar as estimativas populacionais por estado e condado
# Podemos carregar os dados e usando set_index() para combinar valores de estados e de condados.

df.set_index(['STNAME', 'CTYNAME'], inplace = True)
df.head(10)

                         BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME
Alabama Autauga County          151         636         615         574
        Baldwin County          517        2187        2092        2160
        Barbour County           70         335         300         283
        Bibb County              44         266         245         259
        Blount County           183         744         710         646
        Bullock County           39         169         122         132
        Butler County            65         276         241         240
        Calhoun County          317        1382        1357        1309
        Chambers County          81         401         393         404
        Cherokee County          55         221         245         232

                         BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County          623         600            54660
        Baldwin County         2186        2240           183193
        Barbour County          260         269            27341
        Bibb County             247         253            22861
        Blount County           618         603            57373
        Bullock County          118         123            10887
        Butler County           267         257            20944
        Calhoun County         1355        1335           118437
        Chambers County         421         429            34098
        Cherokee County         261         250            25976

                         POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME
Alabama Autauga County             55253            55175            55038
        Baldwin County            186659           190396           195126
        Barbour County             27226            27159            26973
        Bibb County                22733            22642            22512
        Blount County              57711            57776            57734
        Bullock County             10629            10606            10628
        Butler County              20673            20408            20261
        Calhoun County            117768           117286           116575
        Chambers County            33993            34075            34153
        Cherokee County            26080            26023            26084

                         POPESTIMATE2014  POPESTIMATE2015
STNAME  CTYNAME
Alabama Autauga County             55290            55347
        Baldwin County            199713           203709
        Barbour County             26815            26489
        Bibb County                22549            22583
        Blount County              57658            57673
        Bullock County             10829            10696
        Butler County              20276            20154
        Calhoun County            115993           115620
        Chambers County            34052            34123
        Cherokee County            25995            25859

In [ ]:
# Como podemos consultar esse DataFrame?
# Por exemplo, vimos que o atributo "loc" do DataFrame pode ter vários argumentos, e ele poderia consultar ambas linhas e colunas.
# Quando usamos multi-index precisamos fornecer os argumentos na ordem do nível que desejamos consultar. Dentro do índice, cada coluna é chamada de 'nível', de modo que a coluna mais externa é o nível zero. 

# Então, se quisermos ver os resultados da população do condado de Washtenaw, no estado de Michigan, o primeiro argumento seria "Michigan" e o segundo "Washtenaw County"
df.loc['Michigan', 'Washtenaw County']

BIRTHS2010            977
BIRTHS2011           3826
BIRTHS2012           3780
BIRTHS2013           3662
BIRTHS2014           3683
BIRTHS2015           3709
POPESTIMATE2010    345563
POPESTIMATE2011    349048
POPESTIMATE2012    351213
POPESTIMATE2013    354289
POPESTIMATE2014    357029
POPESTIMATE2015    358880
Name: (Michigan, Washtenaw County), dtype: int64

In [ ]:
# E se quisermos filtrar apenas duas colunas? 
# Nesse caso, precisamos NECESSARIAMENTE passar os níveis entre TUPLAS, para conseguirmos separar as colunas
df.loc[('Michigan', 'Washtenaw County'), ['BIRTHS2010', 'BIRTHS2011', 'BIRTHS2012']]

BIRTHS2010     977
BIRTHS2011    3826
BIRTHS2012    3780
Name: (Michigan, Washtenaw County), dtype: int64

In [50]:
# E se quisermos filtrar mais níveis?
# Então devemos passar uma lista de tuplas
df.loc[[('Michigan', 'Washtenaw County'), ('Alabama', 'Autauga County')], ['BIRTHS2010', 'BIRTHS2011', 'BIRTHS2012']]

                           BIRTHS2010  BIRTHS2011  BIRTHS2012
STNAME   CTYNAME
Michigan Washtenaw County         977        3826        3780
Alabama  Autauga County           151         636         615

In [ ]:
# Se for o mesmo nível 0 mas diferentes níveis 1, podemos utilizar a tupla, com uma lista dentro da tupla
df.loc[('Alabama', ['Autauga County', 'Baldwin County']), ['BIRTHS2010', 'BIRTHS2011', 'BIRTHS2012']]


# Isso evita ter que ficar repetindo Alabama, por exemplo, df.loc[[('Alabama', 'Autauga County'), ('Alabama', 'Baldwin County')], ['BIRTHS2010', 'BIRTHS2011']]

                        BIRTHS2010  BIRTHS2011
STNAME  CTYNAME
Alabama Autauga County         151         636
        Baldwin County         517        2187

Acessar um índice composto específico  
df.loc[('nivel0', 'nivel1')]

Acessar um índice composto + colunas específicas  
df.loc[('nivel0', 'nivel1'), ['COL1', 'COL2']]

Acessar todos os valores de um nível 0  
df.loc['nivel0']

Mesmo nível 0, vários nível 1  
df.loc[('nivel0', ['nivel1a', 'nivel1b'])]

Mesmo nível 0, vários nível 1 + colunas específicas  
df.loc[('nivel0', ['nivel1a', 'nivel1b']), ['COL1', 'COL2']]

Vários pares específicos  
df.loc[
    [
        ('nivel0a', 'nivel1a'),
        ('nivel0b', 'nivel1b')
    ]
]