# Tratamento de conflitos entre DataFrames

In [3]:
# O que acontece quando temos conflitos entre os DataFrames? 
# Vamos analisar criando novos DataFrames para funcionários e estudantes, das quais tenham informações de localização.

# Importando a biblioteca
import pandas as pd

# Vamos criar dois dataframes, um de funcionários e um de estudantes
funcionarios_df = pd.DataFrame([{'Nome': 'Kelly', 'Funcao': 'Diretor de RH', 'Localizacao': 'DP 1'},
                                {'Nome': 'Sally', 'Funcao': 'Ligação do Curso', 'Localizacao': 'DP 2'},
                                {'Nome': 'James', 'Funcao': 'Avaliador', 'Localizacao': 'DP 2'}])

# Vamos indexar esses funcionarios pelo nome:
funcionarios_df.set_index('Nome', inplace = True)

# Dataframe de alunos
estudantes_df = pd.DataFrame([{'Nome': 'James', 'Curso': 'Negócios', 'Localizacao': 'Rua 1'},
                           {'Nome': 'Mike', 'Curso': 'Advocacia', 'Localizacao': 'Rua 2'},
                           {'Nome': 'Sally', 'Curso': 'Engenharia', 'Localizacao': 'Rua 3'}])

# Vamos indexar esses estudantes pelo nome:
estudantes_df = estudantes_df.set_index('Nome')

Perceba que no DataFrame de funcionários, a localização é do departamento, por exemplo, DP 2 onde podemos encontrar a pessoa da equipe. Contudo, no DataFrame de estudantes, a localização é do endereço do aluno (endereço residencial).

A função de mesclagem preserva essas informações, mas depende de _x ou _y para ajudar a diferenciar qual índice combinou com qual coluna de dados.

- O _x é sempre a informação do DataFrame a esquerda 
- O _y é sempre a informação de dados do DataFrame a direita

In [5]:
# Vamos fazer o left join

pd.merge(funcionarios_df, estudantes_df, how = 'left', on = 'Nome')

                 Funcao Localizacao_x       Curso Localizacao_y
Nome
Kelly     Diretor de RH          DP 1         NaN           NaN
Sally  Ligação do Curso          DP 2  Engenharia         Rua 3
James         Avaliador          DP 2    Negócios         Rua 1

Perceba que Localizacao_x representa a localização presente no DataFrame de funcionários, enquanto a Localizacao_y representa a localização presente no DataFrame de estudantes.

In [9]:
# Podemos nomear os sufixos da localização, ou de um atributo em conflito, utilizando o parâmetro 'suffixes('_df-esquerdo', '_df-direito')

pd.merge(funcionarios_df, estudantes_df, how = 'left', on = 'Nome', suffixes = (' departamento', '_residência'))

,Funcao,Localizacao departamento,Curso,Localizacao_residência
Nome,,,,
Kelly,Diretor de RH,DP 1,NaN,NaN
Sally,Ligação do Curso,DP 2,Engenharia,Rua 3
James,Avaliador,DP 2,Negócios,Rua 1

##### Multi-indexação e várias colunas

In [11]:
# É bem possível que o primeiro nome de estudantes e funcionários se sobreponham, mas o sobrenome não. Nesse caso, podemos usar uma lista de várias colunas que devem ser usadas para unir chaves de ambos os DataFrames usando o parâmetro 'on'. 
# Lembre-se de que os nomes das colunas atribuídos ao parâmetro precisam existir nos dois DataFrames 

# Exemplo
funcionarios_df = pd.DataFrame([{'Primeiro Nome': 'Kelly', 'Sobrenome': 'Desjardins', 
                          'Função': 'Diretor de RH'},
                         {'Primeiro Nome': 'Sally', 'Sobrenome': 'Brooks', 
                          'Função': 'Ligação de Curso'},
                         {'Primeiro Nome': 'James', 'Sobrenome': 'Wilde', 
                          'Função': 'Avaliador'}])

estudantes_df = pd.DataFrame([{'Primeiro Nome': 'James', 'Sobrenome': 'Hammond', 
                            'Curso': 'Negócios'},
                           {'Primeiro Nome': 'Mike', 'Sobrenome': 'Smith', 
                            'Curso': 'Advocacia'},
                           {'Primeiro Nome': 'Sally', 'Sobrenome': 'Brooks', 
                            'Curso': 'Engenharia'}])

display(funcionarios_df)
display(estudantes_df)

  Primeiro Nome   Sobrenome            Função
0         Kelly  Desjardins     Diretor de RH
1         Sally      Brooks  Ligação de Curso
2         James       Wilde         Avaliador

  Primeiro Nome Sobrenome       Curso
0         James   Hammond    Negócios
1          Mike     Smith   Advocacia
2         Sally    Brooks  Engenharia

Perceba que James Wilde e James Hammond não coicidem nos dois nomes, pois têm sobrenomes diferentes, então esperamos que uma **interseção** não seja incluído esses indivíduos, e sobre apenas a Sally, uma vez que apenas ela é tanto estudante quanto funcionária.

In [17]:
# Para termos uma indexação de várias colunas, basta utilizar uma lista com os nomes das colunas

pd.merge(funcionarios_df, estudantes_df, how = 'inner', on = ['Primeiro Nome', 'Sobrenome'])

  Primeiro Nome Sobrenome            Função       Curso
0         Sally    Brooks  Ligação de Curso  Engenharia