# Group by

Às vezes, queremos selecionar dados com base em grupos e entender os dados agregados no nível do grupo. Dessa forma, em muitas análises de dados, queremos agrupar registros que possuem alguma característica em comum e então calcular estatísticas ou agregações para cada grupo. Por exemplo, podemos querer calcular a média de vendas por estado, a soma de população por cidade ou o número de alunos por curso.

Embora o Pandas permita iterar linha por linha em um DataFrame, essa abordagem é geralmente muito lenta e não é considerada idiomática. Sendo assim, para resolver esse tipo de problema de forma eficiente, o Pandas fornece o método groupby(). <br>
A ideia do groupby() é dividir o DataFrame em subconjuntos com base em uma ou mais colunas (chaves de agrupamento). Depois que os dados são divididos, podemos aplicar operações em cada grupo separadamente, como soma, média, contagem, máximo ou funções personalizadas.

O funcionamento do groupby segue um padrão muito importante na análise de dados, chamado split-apply-combine (dividir-aplicar-combinar):

1) Split (Dividir) <br>
O DataFrame é dividido em vários grupos com base nos valores de uma ou mais colunas.

2) Apply (Aplicar) <br>
Uma função é aplicada independentemente a cada grupo. Essa função pode ser uma agregação (mean, sum, count), uma transformação ou até uma função personalizada.

3) Combine (Combinar) <br>
Os resultados de cada grupo são combinados novamente em uma nova estrutura (normalmente um DataFrame ou uma Series).

Esse padrão é extremamente poderoso porque permite realizar operações complexas em grandes conjuntos de dados de forma vetorizada e muito mais eficiente do que iterar manualmente sobre as linhas.

In [2]:
# Importando as bibliotecas
import numpy as np
import pandas as pd

#### 1 - Splitting

In [57]:
# Vamos dar uma olhada em um exemplo.
# Vamos novamente dar uma olhada em alguns dados do censo dos EUA 

df = pd.read_csv('datasets/census.csv')

# Agora, vamos excluir resumos em nível estadual (que têm valor de 40), ou seja, vamos manter aqueles que têm valor de 50.
df = df[df['SUMLEV'] == 50]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

Para este exemplo de groupby(), utilizaremos o conjunto de dados do censo. O objetivo é calcular a população média dos condados (CENSUS2010POP) em cada estado (STNAME).

Antes de usar groupby(), vamos resolver o problema de forma manual, iterando sobre os estados. Isso servirá para mostrar por que essa abordagem não é a mais eficiente em Pandas.

Primeiro, obtemos uma lista com todos os estados únicos do DataFrame usando: df['STNAME'].unique(). Lembrando que isso retorna um array contendo cada estado apenas uma vez.

Vamos executar essa tarefa três vezes e cronometrá-la. Para isso, usaremos a magic function %%timeit.

In [ ]:
%%timeit -n 3

for state in df['STNAME'].unique():
    # Vamos apenas calcular a média usando o numpy para esse estado específico.
    media = np.average(df.loc[df['STNAME'] == state, 'CENSUS2010POP'])

    # Vamos imprimir na tela
    print(f'Condados do estado {state}\nPopulação média de {str(media)} ')

Condados em estado Alabama
População média de 71339.34328358209
Condados em estado Alaska
População média de 24490.724137931036
Condados em estado Arizona
População média de 426134.4666666667
Condados em estado Arkansas
População média de 38878.90666666667
Condados em estado California
População média de 642309.5862068966
Condados em estado Colorado
População média de 78581.1875
Condados em estado Connecticut
População média de 446762.125
Condados em estado Delaware
População média de 299311.3333333333
Condados em estado District of Columbia
População média de 601723.0
Condados em estado Florida
População média de 280616.5671641791
Condados em estado Georgia
População média de 60928.63522012578
Condados em estado Hawaii
População média de 272060.2
Condados em estado Idaho
População média de 35626.86363636364
Condados em estado Illinois
População média de 125790.50980392157
Condados em estado Indiana
População média de 70476.10869565218
Condados em estado Iowa
População média de 30771.262626262625
Condados em estado Kansas
População média de 27172.55238095238
Condados em estado Kentucky
População média de 36161.39166666667
Condados em estado Louisiana
População média de 70833.9375
Condados em estado Maine
População média de 83022.5625
Condados em estado Maryland
População média de 240564.66666666666
Condados em estado Massachusetts
População média de 467687.78571428574
Condados em estado Michigan
População média de 119080.0
Condados em estado Minnesota
População média de 60964.65517241379
Condados em estado Mississippi
População média de 36186.54878048781
Condados em estado Missouri
População média de 52077.62608695652
Condados em estado Montana
População média de 17668.125
Condados em estado Nebraska
População média de 19638.075268817203
Condados em estado Nevada
População média de 158855.9411764706
Condados em estado New Hampshire
População média de 131647.0
Condados em estado New Jersey
População média de 418661.61904761905
Condados em estado New Mexico
População média de 62399.36363636364
Condados em estado New York
População média de 312550.03225806454
Condados em estado North Carolina
População média de 95354.83
Condados em estado North Dakota
População média de 12690.396226415094
Condados em estado Ohio
População média de 131096.63636363635
Condados em estado Oklahoma
População média de 48718.844155844155
Condados em estado Oregon
População média de 106418.72222222222
Condados em estado Pennsylvania
População média de 189587.74626865672
Condados em estado Rhode Island
População média de 210513.4
Condados em estado South Carolina
População média de 100551.39130434782
Condados em estado South Dakota
População média de 12336.060606060606
Condados em estado Tennessee
População média de 66801.1052631579
Condados em estado Texas
População média de 98998.27165354331
Condados em estado Utah
População média de 95306.37931034483
Condados em estado Vermont
População média de 44695.78571428572
Condados em estado Virginia
População média de 60111.29323308271
Condados em estado Washington
População média de 172424.10256410256
Condados em estado West Virginia
População média de 33690.8
Condados em estado Wisconsin
População média de 78985.91666666667
Condados em estado Wyoming
População média de 24505.478260869564
Condados em estado Alabama
População média de 71339.34328358209
Condados em estado Alaska
População média de 24490.724137931036
Condados em estado Arizona
População média de 426134.4666666667
Condados em estado Arkansas
População média de 38878.90666666667
Condados em estado California
População média de 642309.5862068966
Condados em estado Colorado
População média de 78581.1875
Condados em estado Connecticut
População média de 446762.125
Condados em estado Delaware
População média de 299311.3333333333
Condados em estado District of Columbia
População média de 601723.0
Condados em estado Florida
População média de 280616.5671641791
Condados em estado Georgia
População média de 60928.63522012578
Condados em estado Hawaii
População média de 272060.2
Condados em estado Idaho
População média de 35626.86363636364
Condados em estado Illinois
População média de 125790.50980392157
Condados em estado Indiana
População média de 70476.10869565218
Condados em estado Iowa
População média de 30771.262626262625
Condados em estado Kansas
População média de 27172.55238095238
Condados em estado Kentucky
População média de 36161.39166666667
Condados em estado Louisiana
População média de 70833.9375
Condados em estado Maine
População média de 83022.5625
Condados em estado Maryland
População média de 240564.66666666666
Condados em estado Massachusetts
População média de 467687.78571428574
Condados em estado Michigan
População média de 119080.0
Condados em estado Minnesota
População média de 60964.65517241379
Condados em estado Mississippi
População média de 36186.54878048781
Condados em estado Missouri
População média de 52077.62608695652
Condados em estado Montana
População média de 17668.125
Condados em estado Nebraska
População média de 19638.075268817203
Condados em estado Nevada
População média de 158855.9411764706
Condados em estado New Hampshire
População média de 131647.0
Condados em estado New Jersey
População média de 418661.61904761905
Condados em estado New Mexico
População média de 62399.36363636364
Condados em estado New York
População média de 312550.03225806454
Condados em estado North Carolina
População média de 95354.83
Condados em estado North Dakota
População média de 12690.396226415094
Condados em estado Ohio
População média de 131096.63636363635
Condados em estado Oklahoma
População média de 48718.844155844155
Condados em estado Oregon
População média de 106418.72222222222
Condados em estado Pennsylvania
População média de 189587.74626865672
Condados em estado Rhode Island
População média de 210513.4
Condados em estado South Carolina
População média de 100551.39130434782
Condados em estado South Dakota
População média de 12336.060606060606
Condados em estado Tennessee
População média de 66801.1052631579
Condados em estado Texas
População média de 98998.27165354331
Condados em estado Utah
População média de 95306.37931034483
Condados em estado Vermont
População média de 44695.78571428572
Condados em estado Virginia
População média de 60111.29323308271
Condados em estado Washington
População média de 172424.10256410256
Condados em estado West Virginia
População média de 33690.8
Condados em estado Wisconsin
População média de 78985.91666666667
Condados em estado Wyoming
População média de 24505.478260869564
Condados em estado Alabama
População média de 71339.34328358209
Condados em estado Alaska
População média de 24490.724137931036
Condados em estado Arizona
População média de 426134.4666666667
Condados em estado Arkansas
População média de 38878.90666666667
Condados em estado California
População média de 642309.5862068966
Condados em estado Colorado
População média de 78581.1875
Condados em estado Connecticut
População média de 446762.125
Condados em estado Delaware
População média de 299311.3333333333
Condados em estado District of Columbia
População média de 601723.0
Condados em estado Florida
População média de 280616.5671641791
Condados em estado Georgia
População média de 60928.63522012578
Condados em estado Hawaii
População média de 272060.2
Condados em estado Idaho
População média de 35626.86363636364
Condados em estado Illinois
População média de 125790.50980392157
Condados em estado Indiana
População média de 70476.10869565218
Condados em estado Iowa
População média de 30771.262626262625
Condados em estado Kansas
População média de 27172.55238095238
Condados em estado Kentucky
População média de 36161.39166666667
Condados em estado Louisiana
População média de 70833.9375
Condados em estado Maine
População média de 83022.5625
Condados em estado Maryland
População média de 240564.66666666666
Condados em estado Massachusetts
População média de 467687.78571428574
Condados em estado Michigan
População média de 119080.0
Condados em estado Minnesota
População média de 60964.65517241379
Condados em estado Mississippi
População média de 36186.54878048781
Condados em estado Missouri
População média de 52077.62608695652
Condados em estado Montana
População média de 17668.125
Condados em estado Nebraska
População média de 19638.075268817203
Condados em estado Nevada
População média de 158855.9411764706
Condados em estado New Hampshire
População média de 131647.0
Condados em estado New Jersey
População média de 418661.61904761905
Condados em estado New Mexico
População média de 62399.36363636364
Condados em estado New York
População média de 312550.03225806454
Condados em estado North Carolina
População média de 95354.83
Condados em estado North Dakota
População média de 12690.396226415094
Condados em estado Ohio
População média de 131096.63636363635
Condados em estado Oklahoma
População média de 48718.844155844155
Condados em estado Oregon
População média de 106418.72222222222
Condados em estado Pennsylvania
População média de 189587.74626865672
Condados em estado Rhode Island
População média de 210513.4
Condados em estado South Carolina
População média de 100551.39130434782
Condados em estado South Dakota
População média de 12336.060606060606
Condados em estado Tennessee
População média de 66801.1052631579
Condados em estado Texas
População média de 98998.27165354331
Condados em estado Utah
População média de 95306.37931034483
Condados em estado Vermont
População média de 44695.78571428572
Condados em estado Virginia
População média de 60111.29323308271
Condados em estado Washington
População média de 172424.10256410256
Condados em estado West Virginia
População média de 33690.8
Condados em estado Wisconsin
População média de 78985.91666666667
Condados em estado Wyoming
População média de 24505.478260869564
Condados em estado Alabama
População média de 71339.34328358209
Condados em estado Alaska
População média de 24490.724137931036
Condados em estado Arizona
População média de 426134.4666666667
Condados em estado Arkansas
População média de 38878.90666666667
Condados em estado California
População média de 642309.5862068966
Condados em estado Colorado
População média de 78581.1875
Condados em estado Connecticut
População média de 446762.125
Condados em estado Delaware
População média de 299311.3333333333
Condados em estado District of Columbia
População média de 601723.0
Condados em estado Florida
População média de 280616.5671641791
Condados em estado Georgia
População média de 60928.63522012578
Condados em estado Hawaii
População média de 272060.2
Condados em estado Idaho
População média de 35626.86363636364
Condados em estado Illinois
População média de 125790.50980392157
Condados em estado Indiana
População média de 70476.10869565218
Condados em estado Iowa
População média de 30771.262626262625
Condados em estado Kansas
População média de 27172.55238095238
Condados em estado Kentucky
População média de 36161.39166666667
Condados em estado Louisiana
População média de 70833.9375
Condados em estado Maine
População média de 83022.5625
Condados em estado Maryland
População média de 240564.66666666666
Condados em estado Massachusetts
População média de 467687.78571428574
Condados em estado Michigan
População média de 119080.0
Condados em estado Minnesota
População média de 60964.65517241379
Condados em estado Mississippi
População média de 36186.54878048781
Condados em estado Missouri
População média de 52077.62608695652
Condados em estado Montana
População média de 17668.125
Condados em estado Nebraska
População média de 19638.075268817203
Condados em estado Nevada
População média de 158855.9411764706
Condados em estado New Hampshire
População média de 131647.0
Condados em estado New Jersey
População média de 418661.61904761905
Condados em estado New Mexico
População média de 62399.36363636364
Condados em estado New York
População média de 312550.03225806454
Condados em estado North Carolina
População média de 95354.83
Condados em estado North Dakota
População média de 12690.396226415094
Condados em estado Ohio
População média de 131096.63636363635
Condados em estado Oklahoma
População média de 48718.844155844155
Condados em estado Oregon
População média de 106418.72222222222
Condados em estado Pennsylvania
População média de 189587.74626865672
Condados em estado Rhode Island
População média de 210513.4
Condados em estado South Carolina
População média de 100551.39130434782
Condados em estado South Dakota
População média de 12336.060606060606
Condados em estado Tennessee
População média de 66801.1052631579
Condados em estado Texas
População média de 98998.27165354331
Condados em estado Utah
População média de 95306.37931034483
Condados em estado Vermont
População média de 44695.78571428572
Condados em estado Virginia
População média de 60111.29323308271
Condados em estado Washington
População média de 172424.10256410256
Condados em estado West Virginia
População média de 33690.8
Condados em estado Wisconsin
População média de 78985.91666666667
Condados em estado Wyoming
População média de 24505.478260869564
Condados em estado Alabama
População média de 71339.34328358209
Condados em estado Alaska
População média de 24490.724137931036
Condados em estado Arizona
População média de 426134.4666666667
Condados em estado Arkansas
População média de 38878.90666666667
Condados em estado California
População média de 642309.5862068966
Condados em estado Colorado
População média de 78581.1875
Condados em estado Connecticut
População média de 446762.125
Condados em estado Delaware
População média de 299311.3333333333
Condados em estado District of Columbia
População média de 601723.0
Condados em estado Florida
População média de 280616.5671641791
Condados em estado Georgia
População média de 60928.63522012578
Condados em estado Hawaii
População média de 272060.2
Condados em estado Idaho
População média de 35626.86363636364
Condados em estado Illinois
População média de 125790.50980392157
Condados em estado Indiana
População média de 70476.10869565218
Condados em estado Iowa
População média de 30771.262626262625
Condados em estado Kansas
População média de 27172.55238095238
Condados em estado Kentucky
População média de 36161.39166666667
Condados em estado Louisiana
População média de 70833.9375
Condados em estado Maine
População média de 83022.5625
Condados em estado Maryland
População média de 240564.66666666666
Condados em estado Massachusetts
População média de 467687.78571428574
Condados em estado Michigan
População média de 119080.0
Condados em estado Minnesota
População média de 60964.65517241379
Condados em estado Mississippi
População média de 36186.54878048781
Condados em estado Missouri
População média de 52077.62608695652
Condados em estado Montana
População média de 17668.125
Condados em estado Nebraska
População média de 19638.075268817203
Condados em estado Nevada
População média de 158855.9411764706
Condados em estado New Hampshire
População média de 131647.0
Condados em estado New Jersey
População média de 418661.61904761905
Condados em estado New Mexico
População média de 62399.36363636364
Condados em estado New York
População média de 312550.03225806454
Condados em estado North Carolina
População média de 95354.83
Condados em estado North Dakota
População média de 12690.396226415094
Condados em estado Ohio
População média de 131096.63636363635
Condados em estado Oklahoma
População média de 48718.844155844155
Condados em estado Oregon
População média de 106418.72222222222
Condados em estado Pennsylvania
População média de 189587.74626865672
Condados em estado Rhode Island
População média de 210513.4
Condados em estado South Carolina
População média de 100551.39130434782
Condados em estado South Dakota
População média de 12336.060606060606
Condados em estado Tennessee
População média de 66801.1052631579
Condados em estado Texas
População média de 98998.27165354331
Condados em estado Utah
População média de 95306.37931034483
Condados em estado Vermont
População média de 44695.78571428572
Condados em estado Virginia
População média de 60111.29323308271
Condados em estado Washington
População média de 172424.10256410256
Condados em estado West Virginia
População média de 33690.8
Condados em estado Wisconsin
População média de 78985.91666666667
Condados em estado Wyoming
População média de 24505.478260869564
Condados em estado Alabama
População média de 71339.34328358209
Condados em estado Alaska
População média de 24490.724137931036
Condados em estado Arizona
População média de 426134.4666666667
Condados em estado Arkansas
População média de 38878.90666666667
Condados em estado California
População média de 642309.5862068966
Condados em estado Colorado
População média de 78581.1875
Condados em estado Connecticut
População média de 446762.125
Condados em estado Delaware
População média de 299311.3333333333
Condados em estado District of Columbia
População média de 601723.0
Condados em estado Florida
População média de 280616.5671641791
Condados em estado Georgia
População média de 60928.63522012578
Condados em estado Hawaii
População média de 272060.2
Condados em estado Idaho
População média de 35626.86363636364
Condados em estado Illinois
População média de 125790.50980392157
Condados em estado Indiana
População média de 70476.10869565218
Condados em estado Iowa
População média de 30771.262626262625
Condados em estado Kansas
População média de 27172.55238095238
Condados em estado Kentucky
População média de 36161.39166666667
Condados em estado Louisiana
População média de 70833.9375
Condados em estado Maine
População média de 83022.5625
Condados em estado Maryland
População média de 240564.66666666666
Condados em estado Massachusetts
População média de 467687.78571428574
Condados em estado Michigan
População média de 119080.0
Condados em estado Minnesota
População média de 60964.65517241379
Condados em estado Mississippi
População média de 36186.54878048781
Condados em estado Missouri
População média de 52077.62608695652
Condados em estado Montana
População média de 17668.125
Condados em estado Nebraska
População média de 19638.075268817203
Condados em estado Nevada
População média de 158855.9411764706
Condados em estado New Hampshire
População média de 131647.0
Condados em estado New Jersey
População média de 418661.61904761905
Condados em estado New Mexico
População média de 62399.36363636364
Condados em estado New York
População média de 312550.03225806454
Condados em estado North Carolina
População média de 95354.83
Condados em estado North Dakota
População média de 12690.396226415094
Condados em estado Ohio
População média de 131096.63636363635
Condados em estado Oklahoma
População média de 48718.844155844155
Condados em estado Oregon
População média de 106418.72222222222
Condados em estado Pennsylvania
População média de 189587.74626865672
Condados em estado Rhode Island
População média de 210513.4
Condados em estado South Carolina
População média de 100551.39130434782
Condados em estado South Dakota
População média de 12336.060606060606
Condados em estado Tennessee
População média de 66801.1052631579
Condados em estado Texas
População média de 98998.27165354331
Condados em estado Utah
População média de 95306.37931034483
Condados em estado Vermont
População média de 44695.78571428572
Condados em estado Virginia
População média de 60111.29323308271
Condados em estado Washington
População média de 172424.10256410256
Condados em estado West Virginia
População média de 33690.8
Condados em estado Wisconsin
População média de 78985.91666666667
Condados em estado Wyoming
População média de 24505.478260869564
Condados em estado Alabama
População média de 71339.34328358209
Condados em estado Alaska
População média de 24490.724137931036
Condados em estado Arizona
População média de 426134.4666666667
Condados em estado Arkansas
População média de 38878.90666666667
Condados em estado California
População média de 642309.5862068966
Condados em estado Colorado
População média de 78581.1875

Agora, vamos tentar a abordagem usando groupby

In [ ]:
%%timeit -n 3

# Para esse método, começaremos dizendo ao Pandas que estamosinteressados em agrupar o estado pelo nome, uma vez que essa é a nossa divisão. 
for grupo, frame in df.groupby('STNAME'):
    # Perceba que temos duas variáveis (grupo e frame), isso porque o groupby retorna uma tupla em que o primeiro valor é o valor da chave que estamos tentando agrupar, que nesse caso, é um nome de estado específico, já o segundo é um DataFrame projetado que foi encontrado para esse grupo. Portanto, isso o groupby retorna uma tupla.

    # Agora podemos incluir nossa lógica de cálculo
    media = np.average(frame['CENSUS2010POP'])
    print(f'Condado do estado {grupo}\nPopulação média de {str(media)} ')

Condado do estado Alabama
População média de 71339.34328358209
Condado do estado Alaska
População média de 24490.724137931036
Condado do estado Arizona
População média de 426134.4666666667
Condado do estado Arkansas
População média de 38878.90666666667
Condado do estado California
População média de 642309.5862068966
Condado do estado Colorado
População média de 78581.1875
Condado do estado Connecticut
População média de 446762.125
Condado do estado Delaware
População média de 299311.3333333333
Condado do estado District of Columbia
População média de 601723.0
Condado do estado Florida
População média de 280616.5671641791
Condado do estado Georgia
População média de 60928.63522012578
Condado do estado Hawaii
População média de 272060.2
Condado do estado Idaho
População média de 35626.86363636364
Condado do estado Illinois
População média de 125790.50980392157
Condado do estado Indiana
População média de 70476.10869565218
Condado do estado Iowa
População média de 30771.262626262625
Condado do estado Kansas
População média de 27172.55238095238
Condado do estado Kentucky
População média de 36161.39166666667
Condado do estado Louisiana
População média de 70833.9375
Condado do estado Maine
População média de 83022.5625
Condado do estado Maryland
População média de 240564.66666666666
Condado do estado Massachusetts
População média de 467687.78571428574
Condado do estado Michigan
População média de 119080.0
Condado do estado Minnesota
População média de 60964.65517241379
Condado do estado Mississippi
População média de 36186.54878048781
Condado do estado Missouri
População média de 52077.62608695652
Condado do estado Montana
População média de 17668.125
Condado do estado Nebraska
População média de 19638.075268817203
Condado do estado Nevada
População média de 158855.9411764706
Condado do estado New Hampshire
População média de 131647.0
Condado do estado New Jersey
População média de 418661.61904761905
Condado do estado New Mexico
População média de 62399.36363636364
Condado do estado New York
População média de 312550.03225806454
Condado do estado North Carolina
População média de 95354.83
Condado do estado North Dakota
População média de 12690.396226415094
Condado do estado Ohio
População média de 131096.63636363635
Condado do estado Oklahoma
População média de 48718.844155844155
Condado do estado Oregon
População média de 106418.72222222222
Condado do estado Pennsylvania
População média de 189587.74626865672
Condado do estado Rhode Island
População média de 210513.4
Condado do estado South Carolina
População média de 100551.39130434782
Condado do estado South Dakota
População média de 12336.060606060606
Condado do estado Tennessee
População média de 66801.1052631579
Condado do estado Texas
População média de 98998.27165354331
Condado do estado Utah
População média de 95306.37931034483
Condado do estado Vermont
População média de 44695.78571428572
Condado do estado Virginia
População média de 60111.29323308271
Condado do estado Washington
População média de 172424.10256410256
Condado do estado West Virginia
População média de 33690.8
Condado do estado Wisconsin
População média de 78985.91666666667
Condado do estado Wyoming
População média de 24505.478260869564
Condado do estado Alabama
População média de 71339.34328358209
Condado do estado Alaska
População média de 24490.724137931036
Condado do estado Arizona
População média de 426134.4666666667
Condado do estado Arkansas
População média de 38878.90666666667
Condado do estado California
População média de 642309.5862068966
Condado do estado Colorado
População média de 78581.1875
Condado do estado Connecticut
População média de 446762.125
Condado do estado Delaware
População média de 299311.3333333333
Condado do estado District of Columbia
População média de 601723.0
Condado do estado Florida
População média de 280616.5671641791
Condado do estado Georgia
População média de 60928.63522012578
Condado do estado Hawaii
População média de 272060.2
Condado do estado Idaho
População média de 35626.86363636364
Condado do estado Illinois
População média de 125790.50980392157
Condado do estado Indiana
População média de 70476.10869565218
Condado do estado Iowa
População média de 30771.262626262625
Condado do estado Kansas
População média de 27172.55238095238
Condado do estado Kentucky
População média de 36161.39166666667
Condado do estado Louisiana
População média de 70833.9375
Condado do estado Maine
População média de 83022.5625
Condado do estado Maryland
População média de 240564.66666666666
Condado do estado Massachusetts
População média de 467687.78571428574
Condado do estado Michigan
População média de 119080.0
Condado do estado Minnesota
População média de 60964.65517241379
Condado do estado Mississippi
População média de 36186.54878048781
Condado do estado Missouri
População média de 52077.62608695652
Condado do estado Montana
População média de 17668.125
Condado do estado Nebraska
População média de 19638.075268817203
Condado do estado Nevada
População média de 158855.9411764706
Condado do estado New Hampshire
População média de 131647.0
Condado do estado New Jersey
População média de 418661.61904761905
Condado do estado New Mexico
População média de 62399.36363636364
Condado do estado New York
População média de 312550.03225806454
Condado do estado North Carolina
População média de 95354.83
Condado do estado North Dakota
População média de 12690.396226415094
Condado do estado Ohio
População média de 131096.63636363635
Condado do estado Oklahoma
População média de 48718.844155844155
Condado do estado Oregon
População média de 106418.72222222222
Condado do estado Pennsylvania
População média de 189587.74626865672
Condado do estado Rhode Island
População média de 210513.4
Condado do estado South Carolina
População média de 100551.39130434782
Condado do estado South Dakota
População média de 12336.060606060606
Condado do estado Tennessee
População média de 66801.1052631579
Condado do estado Texas
População média de 98998.27165354331
Condado do estado Utah
População média de 95306.37931034483
Condado do estado Vermont
População média de 44695.78571428572
Condado do estado Virginia
População média de 60111.29323308271
Condado do estado Washington
População média de 172424.10256410256
Condado do estado West Virginia
População média de 33690.8
Condado do estado Wisconsin
População média de 78985.91666666667
Condado do estado Wyoming
População média de 24505.478260869564
Condado do estado Alabama
População média de 71339.34328358209
Condado do estado Alaska
População média de 24490.724137931036
Condado do estado Arizona
População média de 426134.4666666667
Condado do estado Arkansas
População média de 38878.90666666667
Condado do estado California
População média de 642309.5862068966
Condado do estado Colorado
População média de 78581.1875
Condado do estado Connecticut
População média de 446762.125
Condado do estado Delaware
População média de 299311.3333333333
Condado do estado District of Columbia
População média de 601723.0
Condado do estado Florida
População média de 280616.5671641791
Condado do estado Georgia
População média de 60928.63522012578
Condado do estado Hawaii
População média de 272060.2
Condado do estado Idaho
População média de 35626.86363636364
Condado do estado Illinois
População média de 125790.50980392157
Condado do estado Indiana
População média de 70476.10869565218
Condado do estado Iowa
População média de 30771.262626262625
Condado do estado Kansas
População média de 27172.55238095238
Condado do estado Kentucky
População média de 36161.39166666667
Condado do estado Louisiana
População média de 70833.9375
Condado do estado Maine
População média de 83022.5625
Condado do estado Maryland
População média de 240564.66666666666
Condado do estado Massachusetts
População média de 467687.78571428574
Condado do estado Michigan
População média de 119080.0
Condado do estado Minnesota
População média de 60964.65517241379
Condado do estado Mississippi
População média de 36186.54878048781
Condado do estado Missouri
População média de 52077.62608695652
Condado do estado Montana
População média de 17668.125
Condado do estado Nebraska
População média de 19638.075268817203
Condado do estado Nevada
População média de 158855.9411764706
Condado do estado New Hampshire
População média de 131647.0
Condado do estado New Jersey
População média de 418661.61904761905
Condado do estado New Mexico
População média de 62399.36363636364
Condado do estado New York
População média de 312550.03225806454
Condado do estado North Carolina
População média de 95354.83
Condado do estado North Dakota
População média de 12690.396226415094
Condado do estado Ohio
População média de 131096.63636363635
Condado do estado Oklahoma
População média de 48718.844155844155
Condado do estado Oregon
População média de 106418.72222222222
Condado do estado Pennsylvania
População média de 189587.74626865672
Condado do estado Rhode Island
População média de 210513.4
Condado do estado South Carolina
População média de 100551.39130434782
Condado do estado South Dakota
População média de 12336.060606060606
Condado do estado Tennessee
População média de 66801.1052631579
Condado do estado Texas
População média de 98998.27165354331
Condado do estado Utah
População média de 95306.37931034483
Condado do estado Vermont
População média de 44695.78571428572
Condado do estado Virginia
População média de 60111.29323308271
Condado do estado Washington
População média de 172424.10256410256
Condado do estado West Virginia
População média de 33690.8
Condado do estado Wisconsin
População média de 78985.91666666667
Condado do estado Wyoming
População média de 24505.478260869564
Condado do estado Alabama
População média de 71339.34328358209
Condado do estado Alaska
População média de 24490.724137931036
Condado do estado Arizona
População média de 426134.4666666667
Condado do estado Arkansas
População média de 38878.90666666667
Condado do estado California
População média de 642309.5862068966
Condado do estado Colorado
População média de 78581.1875
Condado do estado Connecticut
População média de 446762.125
Condado do estado Delaware
População média de 299311.3333333333
Condado do estado District of Columbia
População média de 601723.0
Condado do estado Florida
População média de 280616.5671641791
Condado do estado Georgia
População média de 60928.63522012578
Condado do estado Hawaii
População média de 272060.2
Condado do estado Idaho
População média de 35626.86363636364
Condado do estado Illinois
População média de 125790.50980392157
Condado do estado Indiana
População média de 70476.10869565218
Condado do estado Iowa
População média de 30771.262626262625
Condado do estado Kansas
População média de 27172.55238095238
Condado do estado Kentucky
População média de 36161.39166666667
Condado do estado Louisiana
População média de 70833.9375
Condado do estado Maine
População média de 83022.5625
Condado do estado Maryland
População média de 240564.66666666666
Condado do estado Massachusetts
População média de 467687.78571428574
Condado do estado Michigan
População média de 119080.0
Condado do estado Minnesota
População média de 60964.65517241379
Condado do estado Mississippi
População média de 36186.54878048781
Condado do estado Missouri
População média de 52077.62608695652
Condado do estado Montana
População média de 17668.125
Condado do estado Nebraska
População média de 19638.075268817203
Condado do estado Nevada
População média de 158855.9411764706
Condado do estado New Hampshire
População média de 131647.0
Condado do estado New Jersey
População média de 418661.61904761905
Condado do estado New Mexico
População média de 62399.36363636364
Condado do estado New York
População média de 312550.03225806454
Condado do estado North Carolina
População média de 95354.83
Condado do estado North Dakota
População média de 12690.396226415094
Condado do estado Ohio
População média de 131096.63636363635
Condado do estado Oklahoma
População média de 48718.844155844155
Condado do estado Oregon
População média de 106418.72222222222
Condado do estado Pennsylvania
População média de 189587.74626865672
Condado do estado Rhode Island
População média de 210513.4
Condado do estado South Carolina
População média de 100551.39130434782
Condado do estado South Dakota
População média de 12336.060606060606
Condado do estado Tennessee
População média de 66801.1052631579
Condado do estado Texas
População média de 98998.27165354331
Condado do estado Utah
População média de 95306.37931034483
Condado do estado Vermont
População média de 44695.78571428572
Condado do estado Virginia
População média de 60111.29323308271
Condado do estado Washington
População média de 172424.10256410256
Condado do estado West Virginia
População média de 33690.8
Condado do estado Wisconsin
População média de 78985.91666666667
Condado do estado Wyoming
População média de 24505.478260869564
Condado do estado Alabama
População média de 71339.34328358209
Condado do estado Alaska
População média de 24490.724137931036
Condado do estado Arizona
População média de 426134.4666666667
Condado do estado Arkansas
População média de 38878.90666666667
Condado do estado California
População média de 642309.5862068966
Condado do estado Colorado
População média de 78581.1875
Condado do estado Connecticut
População média de 446762.125
Condado do estado Delaware
População média de 299311.3333333333
Condado do estado District of Columbia
População média de 601723.0
Condado do estado Florida
População média de 280616.5671641791
Condado do estado Georgia
População média de 60928.63522012578
Condado do estado Hawaii
População média de 272060.2
Condado do estado Idaho
População média de 35626.86363636364
Condado do estado Illinois
População média de 125790.50980392157
Condado do estado Indiana
População média de 70476.10869565218
Condado do estado Iowa
População média de 30771.262626262625
Condado do estado Kansas
População média de 27172.55238095238
Condado do estado Kentucky
População média de 36161.39166666667
Condado do estado Louisiana
População média de 70833.9375
Condado do estado Maine
População média de 83022.5625
Condado do estado Maryland
População média de 240564.66666666666
Condado do estado Massachusetts
População média de 467687.78571428574
Condado do estado Michigan
População média de 119080.0
Condado do estado Minnesota
População média de 60964.65517241379
Condado do estado Mississippi
População média de 36186.54878048781
Condado do estado Missouri
População média de 52077.62608695652
Condado do estado Montana
População média de 17668.125
Condado do estado Nebraska
População média de 19638.075268817203
Condado do estado Nevada
População média de 158855.9411764706
Condado do estado New Hampshire
População média de 131647.0
Condado do estado New Jersey
População média de 418661.61904761905
Condado do estado New Mexico
População média de 62399.36363636364
Condado do estado New York
População média de 312550.03225806454
Condado do estado North Carolina
População média de 95354.83
Condado do estado North Dakota
População média de 12690.396226415094
Condado do estado Ohio
População média de 131096.63636363635
Condado do estado Oklahoma
População média de 48718.844155844155
Condado do estado Oregon
População média de 106418.72222222222
Condado do estado Pennsylvania
População média de 189587.74626865672
Condado do estado Rhode Island
População média de 210513.4
Condado do estado South Carolina
População média de 100551.39130434782
Condado do estado South Dakota
População média de 12336.060606060606
Condado do estado Tennessee
População média de 66801.1052631579
Condado do estado Texas
População média de 98998.27165354331
Condado do estado Utah
População média de 95306.37931034483
Condado do estado Vermont
População média de 44695.78571428572
Condado do estado Virginia
População média de 60111.29323308271
Condado do estado Washington
População média de 172424.10256410256
Condado do estado West Virginia
População média de 33690.8
Condado do estado Wisconsin
População média de 78985.91666666667
Condado do estado Wyoming
População média de 24505.478260869564
Condado do estado Alabama
População média de 71339.34328358209
Condado do estado Alaska
População média de 24490.724137931036
Condado do estado Arizona
População média de 426134.4666666667
Condado do estado Arkansas
População média de 38878.90666666667
Condado do estado California
População média de 642309.5862068966
Condado do estado Colorado
População média de 78581.1875
Condado do estado Connecticut
População média de 446762.125
Condado do estado Delaware
População média de 299311.3333333333
Condado do estado District of Columbia
População média de 601723.0
Condado do estado Florida
População média de 280616.5671641791
Condado do estado Georgia
População média de 60928.63522012578
Condado do estado Hawaii
População média de 272060.2
Condado do estado Idaho
População média de 35626.86363636364
Condado do estado Illinois
População média de 125790.50980392157
Condado do estado Indiana
População média de 70476.10869565218
Condado do estado Iowa
População média de 30771.262626262625
Condado do estado Kansas
População média de 27172.55238095238
Condado do estado Kentucky
População média de 36161.39166666667
Condado do estado Louisiana
População média de 70833.9375
Condado do estado Maine
População média de 83022.5625
Condado do estado Maryland
População média de 240564.66666666666
Condado do estado Massachusetts
População média de 467687.78571428574
Condado do estado Michigan
População média de 119080.0
Condado do estado Minnesota
População média de 60964.65517241379
Condado do estado Mississippi
População média de 36186.54878048781
Condado do estado Missouri
População média de 52077.62608695652
Condado do estado Montana
População média de 17668.125
Condado do estado Nebraska
População média de 19638.075268817203
Condado do estado Nevada
População média de 158855.9411764706
Condado do estado New Hampshire
População média de 131647.0
Condado do estado New Jersey
População média de 418661.61904761905
Condado do estado New Mexico
População média de 62399.36363636364
Condado do estado New York
População média de 312550.03225806454
Condado do estado North Carolina
População média de 95354.83
Condado do estado North Dakota
População média de 12690.396226415094
Condado do estado Ohio
População média de 131096.63636363635
Condado do estado Oklahoma
População média de 48718.844155844155
Condado do estado Oregon
População média de 106418.72222222222
Condado do estado Pennsylvania
População média de 189587.74626865672
Condado do estado Rhode Island
População média de 210513.4
Condado do estado South Carolina
População média de 100551.39130434782
Condado do estado South Dakota
População média de 12336.060606060606
Condado do estado Tennessee
População média de 66801.1052631579
Condado do estado Texas
População média de 98998.27165354331
Condado do estado Utah
População média de 95306.37931034483
Condado do estado Vermont
População média de 44695.78571428572
Condado do estado Virginia
População média de 60111.29323308271
Condado do estado Washington
População média de 172424.10256410256
Condado do estado West Virginia
População média de 33690.8
Condado do estado Wisconsin
População média de 78985.91666666667
Condado do estado Wyoming
População média de 24505.478260869564
Condado do estado Alabama
População média de 71339.34328358209
Condado do estado Alaska
População média de 24490.724137931036
Condado do estado Arizona
População média de 426134.4666666667
Condado do estado Arkansas
População média de 38878.90666666667
Condado do estado California
População média de 642309.5862068966
Condado do estado Colorado
População média de 78581.1875
Condado do estado Connecticut
População média de 446762.125
Condado do estado Delaware
População média de 299311.3333333333
Condado do estado District of Columbia
População média de 601723.0
Condado do estado Florida
População média de 280616.5671641791
Condado do estado Georgia
População média de 60928.63522012578

Perceba que a diferença é metade do tempo:
- Para o primeiro caso: 30.8 ms ± 3.49 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)
- Usando groupby: 14.4 ms ± 2.83 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)

In [38]:
# Um ponto importante, é que o groupby() não retorna um DataFrame, ele retorna um objeto especial chamado DataFrameGroupBy. Esse objeto funciona de forma lazy (preguiçosa) igual a função map(), uma vez que ele apenas define os grupos, mas não calcula nada ainda, com o objetivo de economizar memória. 

# Criando o groupby
grupos = df.groupby('STNAME')
print(f'Tipo do grupo: {type(grupos)}')

# Agora precisamos iterar sobre os grupos, ou utilizar o next(). Como já iteramos para calcular a média, vamos usar o next()
estado, frame = next(iter(grupos))

print(f'Estado: {estado}')
display(frame.head())

Tipo do grupo: <class 'pandas.api.typing.DataFrameGroupBy'>
Estado: Alabama

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

Se analisar o frame inteiro, teremos apenas o estado do Alabama.

Também podemos acessar um frame direto pela chave, se essa for conhecida:

In [40]:
# Acessar um grupo específico
df.groupby('STNAME').get_group('Alabama').head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [44]:
# Na forma de dicionário e índice: 
df.groupby('STNAME').groups

{'Alabama': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67], 'Alaska': [69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97], 'Arizona': [99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113], 'Arkansas': [115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189], 'California': [191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248], 'Colorado': [250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313], 'Connecticut': [315, 316, 317, 318, 319, 320, 321, 322], 'Delaware': [324, 325, 326], 'District of Columbia': [328], 'Florida': [330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396], 'Georgia': [398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, ...], 'Hawaii': [558, 559, 560, 561, 562], 'Idaho': [564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607], 'Illinois': [609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, ...], 'Indiana': [712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803], 'Iowa': [805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903], 'Kansas': [905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, ...], 'Kentucky': [1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, ...], 'Louisiana': [1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195], 'Maine': [1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212], 'Maryland': [1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237], 'Massachusetts': [1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252], 'Michigan': [1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336], 'Minnesota': [1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424], 'Mississippi': [1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507], 'Missouri': [1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, ...], 'Montana': [1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680], 'Nebraska': [1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774], 'Nevada': [1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792], 'New Hampshire': [1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803], 'New Jersey': [1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825], 'New Mexico': [1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859], 'New York': [1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922], 'North Carolina': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023], 'North Dakota': [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077], 'Ohio': [2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166], 'Oklahoma': [2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244], 'Oregon': [2246, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281], 'Pennsylvania': [2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349], 'Rhode Island': [2351, 2352, 2353, 2354, 2355], 'South Carolina': [2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402], 'South Dakota': [2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469], 'Tennessee': [2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2564, 2565], 'Texas': [2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, ...], 'Utah': [2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850], 'Vermont': [2852, 2853, 2854, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862, 2863, 2864, 2865], 'Virginia': [2867, 2868, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2908, 2909, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, ...], 'Washington': [3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039], 'West Virginia': [3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095], 'Wisconsin': [3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168], 'Wyoming': [3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192]}

In [ ]:
# 99% das vezes, é usado groupby em uma ou mais colunas. Além disso, também podemos fornecer uma função para o groupby e usá-la para segmentar os dados.

# Vamos supor que temos um grande trabalho em lote com muito processamento e queremos trabalhar apenas em cerca de um terço dos estados em um determinado momento. Nesse caso, poderíamos criar alguma função que retornasse um número entre zero e dois com base no primeiro caractere do nome do estado. Sendo assim, podemos dizer ao groupby que use essa função para dividir nosso DataFrame. 

# ATENÇÃO: É importante observar que, para fazer isso, precisamos definir o índice do DataFrame como a coluna pela qual você deseja agrupar primeiro.

# Criaremos uma nova função chamada definir_numero_lote(), e se o primeiro número, o parâmetro for até M, retornaremos um zero, se for > M até Q, retornaremos um, e caso contrário, retornaremo dois. Em seguida, passaremos essa função para o DataFrame.

# Coluna pela qual vamos agrupar
df = df.set_index('STNAME')

def definir_numero_lote(item: str):
    if item[0] < 'M': # Isso é do Python, por exemplo 'A' < 'M', 'B' < 'M'...
        return 0
    
    if item[0] < 'Q': 
        return 1
    
    return 2

# O DataFrame deve ser agrupado de acordo com o número do lote. Vamos percorrer cada grupo de lotes
for grupo, frame in df.groupby(definir_numero_lote): 
    print(f'Temos {str(len(frame))} registros no grupo, Grupo: {grupo} para processamento')

Temos 1177 registros no grupo, Grupo: 0 para processamento
Temos 1134 registros no grupo, Grupo: 1 para processamento
Temos 831 registros no grupo, Grupo: 2 para processamento

Perceba que dessa vez, não passamos o nome de uma coluna para o groupby(). Em vez disso, definimos o índice do DataFrame como 'STNAME' e, se nenhum identificador de coluna for passado, o groupby usará automaticamente esse índice. 

Função aplicada ao índice: <br>
df.groupby(func)

E se não quisermos definir um índice para isso?

In [ ]:
# Se não quisermos definir um índice, a forma mais indicada é criar uma nova coluna para separação dos dados usando a função map():

df['lote'] = df['STNAME'].map(definir_numero_lote)

for grupo, frame in df.groupby('lote'):
    print(f'Temos {len(frame)} registros no grupo {grupo}')

Temos 1177 registros no grupo 0
Temos 1134 registros no grupo 1
Temos 831 registros no grupo 2

In [60]:
# Ou até mesmo criar uma nova coluna:
for grupo, frame in df.groupby(df['STNAME'].map(definir_numero_lote)):
    print(f'Temos {len(frame)} registros no grupo {grupo}')

Temos 1177 registros no grupo 0
Temos 1134 registros no grupo 1
Temos 831 registros no grupo 2

ATENÇÃO: Podemos utilizar o groupby() com mais de uma coluna, basta passar uma lista de colunas ao invés de uma. 

df.groupby([coluna1, coluna2])

In [67]:
# Vamos supor o DataFrame 
df = pd.DataFrame({
    'Estado': ['SP', 'SP', 'RJ', 'RJ', 'SP'],
    'Cidade': ['Campinas', 'São Paulo', 'Niterói', 'Rio de Janeiro', 'Campinas'],
    'População': [1, 12, 0.5, 6, 1.2]
})

# Agrupando por Estado e Cidade:
df.groupby(['Estado', 'Cidade'])

# Calculando alguma agregação
df.groupby(['Estado', 'Cidade'])['População'].mean()

# Iterando sobre os grupos
for (estado, cidade), frame in df.groupby(['Estado', 'Cidade']):
    print(estado, cidade)
    display(frame)

RJ Niterói

  Estado   Cidade  População
2     RJ  Niterói        0.5

RJ Rio de Janeiro

  Estado          Cidade  População
3     RJ  Rio de Janeiro        6.0

SP Campinas

  Estado    Cidade  População
0     SP  Campinas        1.0
4     SP  Campinas        1.2

SP São Paulo

  Estado     Cidade  População
1     SP  São Paulo       12.0

Vamos ver mais um exemplo de como podemos agrupar os dados

In [69]:
# Vamos dar mais uma olhada em um exemplo de como podemos agrupar dados. 

df = pd.read_csv('datasets/listings.csv')
df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
1,3075044,https://www.airbnb.com/rooms/3075044,20160906204935,2016-09-07,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,9.0,f,NaN,NaN,t,moderate,f,f,1,1.30
2,6976,https://www.airbnb.com/rooms/6976,20160906204935,2016-09-07,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,10.0,f,NaN,NaN,f,moderate,t,f,1,0.47
3,1436513,https://www.airbnb.com/rooms/1436513,20160906204935,2016-09-07,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Most places you find in Boston are small howev...,Come experience the comforts of home away from...,none,Roslindale is a lovely little neighborhood loc...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.00
4,7651065,https://www.airbnb.com/rooms/7651065,20160906204935,2016-09-07,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.25

Nesse conjunto de dados, temos duas colunas de interesse: cancellation_policy (politica de cancelamento) e review_scores_value (valor das avaliações)

In [70]:
# Como podemos agrupar essas duas colunas? 
# Uma primeira abordagem pode ser promovê-los a um índice múltiplo e depois chamar groupby.

df = df.set_index(['cancellation_policy', 'review_scores_value'])

# Quando temos múltiplos índices, precisamos passar os níveis pelos quais estamos interessados em agrupar, uma vez que, por padrão, o groupby() 
for grupo, frame in df.groupby(level = (0, 1)):
    print(grupo)

('flexible', 2.0)
('flexible', 4.0)
('flexible', 5.0)
('flexible', 6.0)
('flexible', 7.0)
('flexible', 8.0)
('flexible', 9.0)
('flexible', 10.0)
('moderate', 2.0)
('moderate', 4.0)
('moderate', 6.0)
('moderate', 7.0)
('moderate', 8.0)
('moderate', 9.0)
('moderate', 10.0)
('strict', 2.0)
('strict', 3.0)
('strict', 4.0)
('strict', 5.0)
('strict', 6.0)
('strict', 7.0)
('strict', 8.0)
('strict', 9.0)
('strict', 10.0)
('super_strict_30', 6.0)
('super_strict_30', 7.0)
('super_strict_30', 8.0)
('super_strict_30', 9.0)
('super_strict_30', 10.0)

In [71]:
# E se quiséssemos agrupar pela política de cancelamento e pelas notas de avaliação, mas separar todas as dezenas das menores de 10 anos?
# Nesse caso, poderíamos usar uma função para gerenciar os agrupamentos. 

def agrupando(item: tuple):
    # Verificaremos a parte do review_scores_value
    if item[1] == 10.0:
        return (item[0], '10.0')
    
    else: 
        return (item[0], 'não é 10.0')

for grupo, frame in df.groupby(by = agrupando):
    print(grupo)

('flexible', '10.0')
('flexible', 'não é 10.0')
('moderate', '10.0')
('moderate', 'não é 10.0')
('strict', '10.0')
('strict', 'não é 10.0')
('super_strict_30', '10.0')
('super_strict_30', 'não é 10.0')